import { readFileSync } from 'node:fs';

export const siteUrl='https://admatieh.github.io/arzware-portfolio-v2/';
const originalHero=readFileSync(new URL('./original-hero.html',import.meta.url),'utf8');
const arrow='<span aria-hidden="true">↗</span>';
const link=(href,text,cls='rev-link')=>`<a class="${cls}" href="${href}">${text}${arrow}</a>`;
const svg=(body,cls='',box='0 0 600 440')=>`<svg class="${cls}" viewBox="${box}" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">${body}</svg>`;
const line=(x1,y1,x2,y2,extra='')=>`<path d="M${x1} ${y1}L${x2} ${y2}" ${extra}/>`;
const dot=(x,y,r=3,extra='')=>`<circle cx="${x}" cy="${y}" r="${r}" ${extra}/>`;
const points=Array.from({length:180},(_,i)=>{const a=i*2.399963,r=155*Math.sqrt((i+.5)/180);return dot(300+Math.cos(a)*r,220+Math.sin(a)*r,.7+(i%3)*.35)}).join('');
const constellation=svg(`<g class="rev-dust">${points}</g><g class="rev-lines">${line(300,220,140,150)}${line(300,220,460,150)}${line(300,220,140,295)}${line(300,220,460,295)}${line(140,150,140,295)}${line(460,150,460,295)}${line(140,150,460,150)}${line(140,295,460,295)}<ellipse cx="300" cy="220" rx="185" ry="76" transform="rotate(-25 300 220)"/><ellipse cx="300" cy="220" rx="185" ry="76" transform="rotate(25 300 220)"/></g><g class="rev-nodes">${dot(300,220,12)}${dot(140,150,5)}${dot(460,150,5)}${dot(140,295,5)}${dot(460,295,5)}</g>`,'rev-constellation');

function radialMap(){
 let paths='',nodes='';
 const point=(r,a)=>[300+r*Math.sin(a),224-r*.72*Math.cos(a)];
 for(let i=0;i<10;i++){const r=105+i*14;let d='';for(let j=0;j<=100;j++){const [x,y]=point(r,Math.PI/3+j/100*Math.PI*4/3);d+=`${j?'L':'M'}${x.toFixed(2)} ${y.toFixed(2)}`}paths+=`<path d="${d}"/>`}
 for(let i=0;i<=16;i++){const a=Math.PI/3+i/16*Math.PI*4/3,[x,y]=point(105,a),[x2,y2]=point(231,a);paths+=line(x,y,x2,y2);if(i%3===0){const [px,py]=point(161,a);nodes+=dot(px,py,4)}}
 paths+=line(300,224,300,60)+line(300,224,300,395);
 return svg(`<g class="rev-map-grid">${paths}</g><g class="rev-map-nodes">${nodes}${dot(300,224,7)}${dot(300,224,23)}${dot(300,68,5)}</g><g class="rev-map-type"><text x="300" y="229" text-anchor="middle">A</text><text x="300" y="35" text-anchor="middle">POSSIBILITY</text><text x="53" y="184">PEOPLE</text><text x="452" y="184">BUSINESSES</text><text x="300" y="428" text-anchor="middle">ONE ACCOUNTABLE OUTCOME</text></g>`,'rev-radial-map');
}

function intro(){return `<section class="rev-intro rev-section" id="about"><div class="rev-section-top"><span class="rev-kicker">A clearer way forward</span><span class="rev-small">Lebanon & beyond</span></div><div class="rev-intro-grid"><h2 class="rev-display rev-reveal">You don't need<br>more technology.<br><em>You need a useful change.</em></h2><div class="rev-intro-copy rev-reveal"><p class="rev-lead">Somewhere between the unanswered message and the fifth spreadsheet, a business starts working harder than it should.</p><p>We look at the whole picture. The customer journey. The repeated tasks. The things people have learned to work around. Then we build or connect the smallest useful move.</p>${link('#diagnosis','Find your starting point')}<div class="rev-intro-note"><span class="rev-spark" aria-hidden="true">✳</span><p>The question comes first.<br>The right system follows.</p></div></div></div></section>`}

function diagnosis(){return `<section class="rev-diagnosis rev-section" id="diagnosis"><div class="rev-section-top"><span class="rev-kicker">01 / Find the friction</span><span class="rev-small">A starting point, not a diagnosis</span></div><div class="rev-split"><div><h2 class="rev-display rev-reveal">Where does<br><em>the work get stuck?</em></h2><p class="rev-copy rev-reveal">Choose the part that feels familiar. We’ll start with the problem underneath it.</p><div class="rev-choice-list" role="group" aria-label="Explore common business needs"><button class="rev-choice" type="button" data-friction="inquiries" aria-pressed="true"><span>01</span>People inquire. The context disappears.${arrow}</button><button class="rev-choice" type="button" data-friction="operations" aria-pressed="false"><span>02</span>The team works from different versions.${arrow}</button><button class="rev-choice" type="button" data-friction="routine" aria-pressed="false"><span>03</span>Good people repeat the same small tasks.${arrow}</button></div></div><div class="rev-friction-visual rev-reveal"><div class="rev-friction-head"><span>A more connected working day</span><span class="rev-status-dot" aria-hidden="true"></span></div><div class="rev-friction-map">${constellation}<span class="rev-friction-center">A shared<br>memory.</span><span class="rev-friction-tag rev-tag-a" data-source="0">Inquiry</span><span class="rev-friction-tag rev-tag-b" data-source="1">Context</span><span class="rev-friction-tag rev-tag-c" data-source="2">Next step</span><span class="rev-friction-tag rev-tag-d" data-source="3">Follow-up</span></div><div class="rev-friction-result" aria-live="polite" aria-atomic="true"><h3 id="friction-title">A conversation that keeps its context.</h3><p id="friction-copy">Connect the first inquiry, the customer’s details, and the next action. Give the follow-up somewhere to live.</p></div></div></div></section>`}

function solutions(){const rows=[['01','A clearer presence','Be found. Be understood.<br><em>Be remembered.</em>','A website should open the right conversation — and help the business carry it forward.',['Websites & landing pages','Customer journeys & clear offers','Inquiry, intake & follow-up']],['02','A connected operation','Give the business<br><em>a shared memory.</em>','Connect the people, information, and next steps that make the working day move.',['CRM-lite & customer records','Bookings, portals & internal tools','Dashboards & shared context']],['03','Room for the human part','Less repetition.<br><em>More possibility.</em>','Let the routine find its rhythm. Keep people responsible for the decisions that matter.',['Workflow automation','Reminders, documents & reports','Human-reviewed AI assistance']]];return `<section class="rev-solutions rev-section" id="solutions"><div class="rev-section-top"><span class="rev-kicker">02 / What we make possible</span><span class="rev-small">Built around the business</span></div><div class="rev-solutions-heading"><h2 class="rev-display rev-reveal">Small moves.<br><em>Connected outcomes.</em></h2><p class="rev-copy rev-reveal">A considered system earns its place by making the day better for the people who use it.</p></div><div class="rev-solution-rows">${rows.map(([n,k,h,p,items])=>`<article class="rev-solution-row rev-reveal"><div class="rev-row-label"><span>${n}</span><p>${k}</p></div><h3>${h}</h3><div><p>${p}</p><details class="rev-details"><summary>What this can include <span aria-hidden="true">+</span></summary><ul>${items.map(x=>`<li>${x}</li>`).join('')}</ul></details></div></article>`).join('')}</div></section>`}

function process(){const rows=[['01','Understand','Follow the business, its customers, and the work behind the work.','A clearer question.'],['02','Diagnose','Find what blocks progress, and the smallest useful move that could change it.','A practical direction.'],['03','Build or connect','Make the right solution, coordinate the right people, or connect what already exists.','Something usable.'],['04','Learn & improve','Test with the people who use it, measure what changes, and choose the next adjustment.','Progress you can see.']];return `<section class="rev-process rev-section rev-paper" id="how-we-work"><div class="rev-section-top"><span class="rev-kicker">03 / How we work</span><span class="rev-small">Attention before action</span></div><div class="rev-process-heading"><h2 class="rev-display rev-reveal">Before we build anything,<br><em>we understand something.</em></h2><p class="rev-copy rev-reveal">Not every problem needs new software.<br>Every useful solution needs the right question.</p></div><ol class="rev-process-list">${rows.map(([n,h,p,note])=>`<li class="rev-process-step rev-reveal"><span class="rev-step-number">${n}</span><div><h3>${h}</h3><p>${p}</p><span class="rev-step-note">${note}</span></div></li>`).join('')}</ol><p class="rev-process-close rev-reveal">The business stays the measure of the work.</p></section>`}

const scenarios={journey:{label:'The customer journey',title:'From an inquiry<br>to a remembered customer.',copy:'A service business can connect its website, inquiry form, bookings, and follow-up. Each conversation arrives with its context, and the next step has an owner.',flow:['Inquiry','Booking','Follow-up'],heading:'A conversation, carried forward',cards:[['New inquiry','A customer has a question.'],['A next step','The team knows what comes next.'],['A shared record','The context stays with the business.']]},team:{label:'The working day',title:'One shared picture.<br>Fewer versions of the truth.',copy:'A growing team can bring customer records, tasks, and status into a clearer shared workspace. People can see what matters without collecting updates from five places.',flow:['People','Information','Next action'],heading:'Everyone sees the same next step',cards:[['Shared context','The information has one home.'],['Clear ownership','Someone knows the next action.'],['A visible status','The team sees where things stand.']]},time:{label:'The repeated task',title:'A routine that runs.<br>Time that comes back.',copy:'A business can connect reminders, recurring documents, and reports into a considered workflow. People review the important parts and keep the final judgment.',flow:['Routine','Review','Ready'],heading:'The routine remembers itself',cards:[['A repeatable task','The right trigger starts the work.'],['A human review','Context and quality stay with people.'],['A useful result','The business knows what happened.']]}};
function scenarioVisual(id){const s=scenarios[id];return `<div class="rev-scenario-head"><span class="rev-status-dot" aria-hidden="true"></span><span>${s.heading}</span><span aria-hidden="true">✳</span></div><div class="rev-scenario-flow">${s.flow.map((f,i)=>`<span>${f}</span>${i<2?'<i aria-hidden="true">→</i>':''}`).join('')}</div><div class="rev-scenario-cards">${s.cards.map(([h,p],i)=>`<div><span class="rev-card-mark" aria-hidden="true">${i===2?'✓':'•'}</span><h4>${h}</h4><p>${p}</p></div>`).join('')}</div><div class="rev-scenario-footer"><span>People keep the judgment.</span><span aria-hidden="true">↗</span></div>`}
function work(){return `<section class="rev-work rev-section" id="work"><div class="rev-section-top"><span class="rev-kicker">04 / A useful change, imagined</span><span class="rev-small">Illustrative scenarios</span></div><div class="rev-work-heading"><h2 class="rev-display rev-reveal">What could<br><em>change for you?</em></h2><p class="rev-copy rev-reveal">These show how a solution can work.<br>They are possibilities to explore, rather than completed client projects.</p></div><div class="rev-work-tabs" role="tablist" aria-label="Solution scenarios">${Object.entries(scenarios).map(([id,s],i)=>`<button role="tab" type="button" id="tab-${id}" data-scenario="${id}" aria-controls="panel-${id}" aria-selected="${i===0}" tabindex="${i===0?'0':'-1'}">${s.label}</button>`).join('')}</div>${Object.entries(scenarios).map(([id,s],i)=>`<div class="rev-work-panel" role="tabpanel" id="panel-${id}" aria-labelledby="tab-${id}" tabindex="0" ${i?'hidden':''}><div class="rev-work-panel-copy"><h3>${s.title}</h3><p>${s.copy}</p>${link('./begin/','Explore this for your business')}</div><div class="rev-scenario">${scenarioVisual(id)}</div></div>`).join('')}</section>`}

function impact(){return `<section class="rev-impact rev-section" id="impact"><div class="rev-section-top"><span class="rev-kicker">05 / The human part</span><span class="rev-small">Opportunity & responsibility</span></div><div class="rev-impact-grid"><div><h2 class="rev-display rev-reveal">Someone once<br>gave you<br><em>a first chance.</em></h2><p class="rev-lead rev-reveal">Talent is everywhere.<br>Opportunity should be, too.</p><p class="rev-copy rev-reveal">We create supervised, real-project opportunities for Lebanese youth. Learning becomes practice. Practice becomes experience. And good work creates room for more people to grow.</p>${link('./people/','Meet the human side')}</div><div class="rev-opportunity-art rev-reveal"><div class="rev-orbit-lines" aria-hidden="true">${constellation}</div><p class="rev-opportunity-quote">A little trust.<br><em>A different future.</em></p><div class="rev-opportunity-path"><span>Learn</span><span>Contribute</span><span>Grow</span></div></div></div><div class="rev-impact-notes"><article class="rev-reveal"><span>01</span><h3>Real work. Real learning.</h3><p>Development, design, AI, research, QA, marketing, and operations. Experience with mentoring and portfolio evidence.</p></article><article class="rev-reveal"><span>02</span><h3>Support with supervision.</h3><p>Research, testing, documentation, and execution support, with Arzware responsible for quality and the outcome.</p></article><article class="rev-reveal"><span>03</span><h3>People stay accountable.</h3><p>Context, privacy, judgment, and the final decision remain with people. Opportunity and responsibility grow together.</p></article></div></section>`}

function ecosystem(){return `<section class="rev-ecosystem rev-section rev-paper"><div class="rev-section-top"><span class="rev-kicker">06 / A connected ecosystem</span><span class="rev-small">The right people around the right need</span></div><div class="rev-ecosystem-grid"><div><h2 class="rev-display rev-reveal">Not every answer<br>is something<br><em>we build alone.</em></h2><p class="rev-copy rev-reveal">Sometimes progress needs a system. Sometimes a collaborator. Sometimes a person who sees the problem differently.</p><p class="rev-copy rev-reveal">We build, coordinate, connect, or bring those paths together around one accountable outcome.</p><p class="rev-ecosystem-people rev-reveal">Businesses · Youth · Startups<br>Agencies · Freelancers · Mentors</p></div><figure class="rev-reveal">${radialMap()}<figcaption>Many paths. One shared possibility.</figcaption></figure></div></section>`}

function faq(){return `<section class="rev-faq rev-section"><div><p class="rev-kicker">Before the first conversation</p><h2 class="rev-display rev-reveal">A few things<br><em>you might wonder.</em></h2></div><div class="rev-faq-list"><details class="rev-details"><summary>Do I need to know what to build? <span aria-hidden="true">+</span></summary><p>No. Bring the business problem, what you’re hoping for, and what seems to be getting in the way. Understanding the need comes before choosing the solution.</p></details><details class="rev-details"><summary>Can you work with our existing tools? <span aria-hidden="true">+</span></summary><p>Yes. We look at what already works before recommending a change. The right move may be a connection between existing tools, a focused improvement, or a new system.</p></details><details class="rev-details"><summary>How do people stay in control of AI? <span aria-hidden="true">+</span></summary><p>AI can assist with research, knowledge, and repeatable work. People remain responsible for privacy, context, quality, and the final decision.</p></details><details class="rev-details"><summary>How can I learn or contribute? <span aria-hidden="true">+</span></summary><p>Write to <a href="mailto:hello@arzware.net?subject=Contributing%20to%20Arzware">hello@arzware.net</a> with a short introduction, what you’re learning, and the kind of work you would like to explore.</p></details></div></section>`}

function review(){return `<section class="rev-review rev-section" id="review"><div class="rev-review-symbol" aria-hidden="true">✳</div><p class="rev-kicker rev-reveal">Your next useful move</p><h2 class="rev-display rev-reveal">Bring us<br><em>the messy part.</em></h2><p class="rev-lead rev-reveal">A missed lead. A repeated task. A process that lives in someone’s head.<br>We’ll start with what’s happening, and work toward what could change.</p><div class="rev-review-actions rev-reveal"><a class="btn-main" href="https://cal.com/arzware" target="_blank" rel="noopener noreferrer">Start a Business Improvement Review <span class="btn-arrow" aria-hidden="true">→</span></a>${link('mailto:hello@arzware.net','hello@arzware.net')}</div><p class="rev-review-note">A business conversation. A clearer question. A practical direction.</p></section>`}

function footer(base){return `<footer class="rev-footer"><div class="rev-footer-top"><a class="rev-footer-brand" href="${base}"><img src="${base}arzware-logo.png" width="40" height="40" alt=""><span>Arzware</span></a><p>Business development<br>through digital innovation.</p><a href="mailto:hello@arzware.net">hello@arzware.net${arrow}</a></div><div class="rev-footer-bottom"><span>© <span data-year>2026</span> Arzware · Lebanon & beyond</span><button type="button" id="motion-toggle" aria-pressed="false">Motion <span>on</span></button><a href="#hero">Back to the beginning ↑</a></div></footer>`}
function head(page,base,path){return `<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0e0e0e"><title>Arzware — ${page.title}</title><meta name="description" content="${page.description}"><link rel="canonical" href="${siteUrl+path}"><meta property="og:type" content="website"><meta property="og:site_name" content="Arzware"><meta property="og:title" content="Arzware — ${page.title}"><meta property="og:description" content="${page.description}"><meta property="og:url" content="${siteUrl+path}"><meta property="og:image" content="${siteUrl}assets/social-preview.jpg"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:image" content="${siteUrl}assets/social-preview.jpg"><link rel="icon" href="${base}favicon.svg" type="image/svg+xml"><link rel="preload" href="${base}assets/fonts/playfair-normal.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="${base}assets/app.css"><script type="module" src="${base}assets/app.js"></script><script type="application/ld+json">{"@context":"https://schema.org","@type":"ProfessionalService","name":"Arzware","url":"${siteUrl}","logo":"${siteUrl}arzware-logo.png","description":"Business development through digital innovation.","areaServed":["Lebanon","Worldwide"],"email":"hello@arzware.net"}</script></head>`}
function fallback(){return `<div class="rev-hero-fallback" aria-hidden="true">${constellation}</div>`}
const content={intro,diagnosis,solutions,process,work,impact,ecosystem,faq,review};
const routes={home:{title:'Business development through digital innovation.',description:'Arzware diagnoses what blocks business growth, then builds or connects the right digital system, AI workflow, or operational solution.',sections:['intro','diagnosis','solutions','process','work','impact','ecosystem','faq','review']},work:{title:'Useful work. Connected outcomes.',description:'Websites, customer journeys, connected operations, and automation shaped around the way your business works.',headline:'Useful work.<br><em>Connected outcomes.</em>',lead:'A clearer presence. A shared memory. A routine that remembers itself.',sections:['solutions','work','review']},way:{title:'Attention before action.',description:'Understand the business, diagnose the need, build or connect the right solution, and improve through real use.',headline:'Before we build,<br><em>we understand.</em>',lead:'A considered way forward, built around the business and the people who use it.',sections:['process','faq','review']},people:{title:'The human side of progress.',description:'Supervised real-project opportunities for Lebanese youth, with mentoring and clear responsibility.',headline:'A first chance.<br><em>A different future.</em>',lead:'Real work. Practical learning. People who remain responsible for the outcome.',sections:['impact','ecosystem','faq','review']},begin:{title:'Bring us the messy part.',description:'Start a business improvement review with Arzware, or write to hello@arzware.net.',headline:'Every useful change<br><em>starts somewhere.</em>',lead:'Bring the business problem, the repeated task, or the idea still finding its shape.',sections:['review','faq']}};

export function renderPages(){return Object.entries(routes).map(([id,page])=>{const home=id==='home',base=home?'./':'../',path=home?'':`${id}/`;let opening;if(home){opening=`<div id="three-container" aria-hidden="true">${fallback()}</div><div class="object-label" id="object-label" aria-hidden="true">Digital Systems</div><div class="layer-blur" aria-hidden="true"></div><div class="noise-overlay" aria-hidden="true"></div><div class="grain-overlay" aria-hidden="true"></div>${originalHero}`;}else{const nav=originalHero.match(/<nav[\s\S]*?<\/nav>/)[0].replaceAll('href="#','href="../#').replaceAll('src="arzware-logo','src="../arzware-logo');opening=`<header class="rev-page-header" id="hero">${nav}</header><div class="rev-page-intro rev-section"><p class="rev-kicker">Arzware / ${id==='way'?'How we work':id==='begin'?'A conversation':id}</p><h1 class="rev-display">${page.headline}</h1><p class="rev-lead">${page.lead}</p></div>`;}const body=page.sections.map(s=>content[s]()).join('').replaceAll('href="./begin/"',`href="${base}begin/"`).replaceAll('href="./people/"',`href="${base}people/"`);return {path:path+'index.html',html:`<!doctype html><html lang="en">${head(page,base,path)}<body class="rev-page-${id}"><a class="skip-link" href="#main-content">Skip to main content</a>${opening}<main id="main-content" class="rev-main">${body}</main>${footer(base)}</body></html>`}})}
